import type { Metadata } from "next";
import Providers from "@/components/Providers";
import Navbar from "@/components/Navbar";
import "@/styles/globals.css";
import Box from "@mui/material/Box";

export const metadata: Metadata = {
  title: "DigiCert Assesment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Box
            sx={{
              display: "flex",
              flexDirection: "column",
              minHeight: "100dvh",
              gap: 4,
              py: 4,
            }}
          >
            <Navbar />
            <main>{children}</main>
          </Box>
        </Providers>
      </body>
    </html>
  );
}
