import type { Metadata } from "next";
import Providers from "@/components/Providers";
import Navbar from "@/components/Navbar";
import "@/styles/globals.css";
import Box from "@mui/material/Box";

export const metadata: Metadata = {
  title: "DigiCert Assesment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body id="__next">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
